services:
    terminal42.dc_multilingual.querybuilder_factory:
        class: Terminal42\DcMultilingualBundle\QueryBuilder\MultilingualQueryBuilderFactory
        public: true
        arguments:
            - "@database_connection"
